"""A hand-wired runner, so you can see what `adk web` hides.

`adk web` is the nicer way to use this agent, but it sets up the Runner and the
session service for you, which means the two objects that matter most stay
invisible. This file wires them by hand and prints the event stream raw.

The two things to watch as you use it:

  1. The [author] tag on every line. That is which agent produced it, and
     watching it change is watching control move through the tree:
     coach -> intake_agent -> coach -> metrics_agent -> workout_designer
     and meal_designer interleaved -> report_agent.

  2. The state line printed after each turn. Keys appear one at a time --
     profile, then targets, then workout_plan and meal_plan together, then
     final_plan. That progression IS the agent-to-agent communication; there
     are no messages passing between these agents, only state.

Run:  .venv/bin/python run_cli.py
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

from dotenv import load_dotenv

# Load the key before importing anything that builds a model client.
load_dotenv(Path(__file__).parent / "workout_agent" / ".env")

from google.adk.runners import Runner            # noqa: E402
from google.adk.sessions import InMemorySessionService  # noqa: E402
from google.genai import types                   # noqa: E402

from workout_agent.agent import root_agent       # noqa: E402
from workout_agent.greeting import generate_opening  # noqa: E402

APP_NAME = "workout_coach"
USER_ID = "learner"
SESSION_ID = "cli-session"

# ANSI colours, purely so the author tags are easy to scan.
DIM, BOLD, CYAN, YELLOW, GREEN, RESET = (
    "\033[2m", "\033[1m", "\033[36m", "\033[33m", "\033[32m", "\033[0m"
)


def render(event) -> None:
    """Print one ADK event, showing who authored it and what kind it was."""
    author = event.author

    # Tool calls and tool results are what delegation actually looks like on
    # the wire -- `transfer_to_agent` is just a function call the model emits.
    for call in event.get_function_calls() or []:
        if call.name == "transfer_to_agent":
            target = (call.args or {}).get("agent_name", "?")
            print(f"{YELLOW}  [{author}] --transfer--> {target}{RESET}")
        else:
            print(f"{CYAN}  [{author}] calls {call.name}({_brief(call.args)}){RESET}")

    for resp in event.get_function_responses() or []:
        print(f"{DIM}  [{author}] {resp.name} returned {_brief(resp.response)}{RESET}")

    # Only print finished text, not partial streaming chunks.
    if event.content and event.content.parts and not event.partial:
        text = "".join(p.text or "" for p in event.content.parts).strip()
        if text:
            print(f"\n{BOLD}[{author}]{RESET} {text}\n")


def _brief(obj, limit: int = 110) -> str:
    s = str(obj)
    return s if len(s) <= limit else s[:limit] + "..."


async def main() -> None:
    session_service = InMemorySessionService()

    # The Runner is the thing that actually drives the agent tree: it appends
    # your message to the session, invokes the root agent, and streams back
    # every event any agent in the tree produces.
    runner = Runner(
        app_name=APP_NAME,
        agent=root_agent,
        session_service=session_service,
    )
    await session_service.create_session(
        app_name=APP_NAME, user_id=USER_ID, session_id=SESSION_ID
    )

    print(f"{BOLD}Weight-loss coach{RESET} {DIM}(ctrl-c or 'quit' to exit){RESET}\n")

    seen: set[str] = set()

    # Make the agent speak first. ADK has no welcome-message setting -- a
    # Runner only runs when handed a user message -- so we send one synthetic
    # "kickoff" turn that you never see. The greeting you read is generated by
    # the model in response to it, not a hardcoded string. See greeting.py.
    opening = await generate_opening(runner, USER_ID, SESSION_ID)
    print(f"{BOLD}[coach]{RESET} {opening}\n")

    while True:
        try:
            line = input(f"{GREEN}you >{RESET} ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            return
        if not line:
            continue
        if line.lower() in {"quit", "exit"}:
            return

        async for event in runner.run_async(
            user_id=USER_ID,
            session_id=SESSION_ID,
            new_message=types.Content(role="user", parts=[types.Part(text=line)]),
        ):
            render(event)

        # Show session state growing. Newly-added keys are highlighted, because
        # the moment a key appears is the moment one agent handed data to the next.
        session = await session_service.get_session(
            app_name=APP_NAME, user_id=USER_ID, session_id=SESSION_ID
        )
        keys = [k for k in (session.state or {}) if not k.startswith("_")]
        if keys:
            shown = [f"{GREEN}{k}*{RESET}" if k not in seen else f"{DIM}{k}{RESET}"
                     for k in keys]
            print(f"{DIM}  state:{RESET} " + " ".join(shown) + "\n")
            seen.update(keys)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        sys.exit(0)
